// <auto-generated />
namespace NTier.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ConnectionStringChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConnectionStringChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202212030913466_ConnectionStringChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
