// <auto-generated />
namespace NTier.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ForSeedData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForSeedData));
        
        string IMigrationMetadata.Id
        {
            get { return "202212110935313_ForSeedData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
